### ISSUE TITLE
Lesson 6 订单 - 6. 云函数`addToOrder` 云函数部署需要完善依赖构建的细节

### ISSUE THREAD

**Issue by aimiy** [udacity/Wechat-Program-Dev-nd666-issues-cn#10]
在视频中，仅仅只是右键点击上传与部署，直接就能够使用该云函数。

但是在实际测试中，我第一次上传部署，会提示没有wx-server-sdk依赖，是否继续上传。运行时也会报错找不到依赖，程序无法运行，我自己安装依赖再上传后就好了。

所以对于新手来说，第一次部署云函数的时候，最好对这一块进行讲解。

**Comment by yangshiyu89** [comment]
嗯嗯，感谢，因为这一章并不是课程第一次讲解云函数。在第四章有解释。
