### ISSUE TITLE
Lesson 8 评论 - Concept 14 上传图片至云端 - 文字错误

### ISSUE THREAD

**Issue by abccdea** [udacity/Wechat-Program-Dev-nd666-issues-cn#12]
文字描述错误，多写了分号

<img width="1096" alt="Screen Shot 2019-05-28 at 16 59 45" src="https://user-images.githubusercontent.com/6440953/58465399-2fcd2200-816a-11e9-8cae-17f43835be5a.png">

[错误地址](https://classroom.udacity.com/nanodegrees/nd666-cn/parts/a953435e-448b-4a0c-b5c0-b9047271ee0f/modules/ea14a377-250e-4772-a561-0ef6e2c5196d/lessons/a961fac2-9875-4650-a3b2-134f7cfead73/concepts/e3221d93-37ec-4e41-ae96-245869203302)

**Comment by yangshiyu89** [comment]
Done
