### ISSUE TITLE
Lesson 8 评论 - Concept 4 获取评论信息 - 文字颜色

### ISSUE THREAD

**Issue by abccdea** [udacity/Wechat-Program-Dev-nd666-issues-cn#13]
文字中代码颜色差一位

<img width="832" alt="Screen Shot 2019-05-29 at 10 57 36" src="https://user-images.githubusercontent.com/6440953/58526261-fbf10b80-8200-11e9-8f4f-a0760c8651ab.png">

[问题链接](https://classroom.udacity.com/nanodegrees/nd666-cn/parts/a953435e-448b-4a0c-b5c0-b9047271ee0f/modules/ea14a377-250e-4772-a561-0ef6e2c5196d/lessons/a961fac2-9875-4650-a3b2-134f7cfead73/concepts/15e2f27d-f15c-4fcc-92b2-f7d76086caa0)

**Comment by yangshiyu89** [comment]
好仔细啊，不过这个是 bug，修改不了。
