### ISSUE TITLE
Lesson 8 评论 - Concept 6  `addReview` 云函数 - 引号多写

### ISSUE THREAD

**Issue by abccdea** [udacity/Wechat-Program-Dev-nd666-issues-cn#14]
代码中引号多了一个，如图：

<img width="831" alt="Screen Shot 2019-05-29 at 16 39 47" src="https://user-images.githubusercontent.com/6440953/58542827-d8de5000-8230-11e9-9507-ebb021c6aa2a.png">

[错误链接](https://classroom.udacity.com/nanodegrees/nd666-cn/parts/a953435e-448b-4a0c-b5c0-b9047271ee0f/modules/ea14a377-250e-4772-a561-0ef6e2c5196d/lessons/a961fac2-9875-4650-a3b2-134f7cfead73/concepts/a359a7d8-cb79-4727-bc59-4c239480d354)

**Comment by yangshiyu89** [comment]
Done
