### ISSUE TITLE
LESSON2 全局配置 - 4.其他 文本有语病

### ISSUE THREAD

**Issue by huxh** [udacity/Wechat-Program-Dev-nd666-issues-cn#16]
视频下方的文本内容直接使用了讲解词，出现诸如“我们重新编译，最终结果为：”这样的语病。建议在文本内容中对视频中的重点内容进行简单总结，而不是直接照搬。
![image](https://user-images.githubusercontent.com/6613942/58739895-9dfe3700-843f-11e9-8c21-d562aa4432f7.png)

**Comment by yangshiyu89** [comment]
Done
