### ISSUE TITLE
LESSON2 搭建商城首页

### ISSUE THREAD

**Issue by AlexShui** [udacity/Wechat-Program-Dev-nd666-issues-cn#20]
课程文字和视频的内容的关系和分类不是很明确，比如一些可以放在视频的同步讲的内容却用文字显示了出来，什么时候用文字，什么用视频，如果能有更明确的定义可能更好，比如所有和实际操作的内容统一放在视频里面，代码和一些页面逻辑的分析等，这样学员对照着视频也能更直观地感受到。

而文字可能用来对即将要观看的视频做一个简单介绍，或者看完后用来做一个简单总结，以及做一些额外的知识点的延伸等。

因为目前优达学城所有可能主要就是几大板块构成，视频，文字，单选题，多选题等，既然是通过不同的板块组合而成的课程，那么每个板块明确独立地负责某些部分可能会比较好。

**Comment by yangshiyu89** [comment]
感谢建议
