### ISSUE TITLE
LESSON2 搭建商城首页 (课程内容没有创意，没有核心亮点)

### ISSUE THREAD

**Issue by AlexShui** [udacity/Wechat-Program-Dev-nd666-issues-cn#21]
课程的讲解方式和内容，完全可以更有创意更独特一些。虽然老师们经验都很丰富，也很认真地讲，但是讲课的方式还是比较官方比较普通的形式，说实话，想象这样一个情况，如果把现在的课程单独拿出来，然后和其他一些视频教学网站比如慕课网作对比，有什么特殊的亮点地方呢？甚至抛开udacity的创始人然后一些很厉害的大神的名号之外，课程本身好像并没有什么能够让学员记忆犹新的地方，如果只是普普通通的教学网站还可以，但是既然udacity有这这么好的背景，就一定要更加注重课程的质量和特色。

像这次的小程序课程，讲解方式和大多数其他视频一样，一个页面一个页面的讲解，但是也许可以换种方式，比如，每个页面都有共同的地方，比如基础骨架和一些通用样式，这种部分在讲解了一个页面后，完全可以举一反三延伸到其他页面。同样地，在数据方面也是，每个页面都不可避免的有数据交互，但是也有一些共同点，比如数据的来源以及数据的出口：

我进入一个页面后，我肯定要有数据对不对？那我数据从哪里来呢？首先可能就是通过api获取，然后可能是从上一个页面传递过来的数据等等，同样地，这些内容都是可以贯穿很多页面的，而且对于以后学员自己的页面，这些内容也是共同的。

而按照页面来分类呢？我们可以给学员讲解10个不同的页面，20个不同的页面，甚至100个页面，但是这样又有什么意义呢？学员总会遇见未知的不属于课程的页面。不管是登录页面还是商品详情页面，我感觉都只是告诉了学员，你现在看见的这个固定样式、固定功能的页面应该怎么完成，而没有提到你现在完成的这个页面体现出了那些重要的概念，为什么我们的课程内容要包含这个页面，它的一些思想对于以后你遇见的问题有什么帮助等等。

我认为吧，一门课程最重要的是利用一些简单的例子，帮助学员入门，然后在这基础上，帮助学员抽象出一些隐藏的核心知识点和模式，让他在完成了这门课程之后甚至以后的很长一段时间内，都能有所帮助，再理想化一点，以后学员听到udacity时，想的不是udacity有多么牛逼的讲师，多么牛逼的背景，而是当初我在udacity某某课程学习到的思想确实很好，即使现在回想起来也很有用。

而现在的课程，说实话。。。确实比较无聊，然后也没什么特别亮眼的地方，如果不是我知道是udacity的，告诉我说是其他哪个小网站的视频可能都没什么毛病。

**Comment by yangshiyu89** [comment]
感谢您的建议。我们会在下一次制作中参考您的建议进行适量更新。制作课程的因素可能会受多方限制，比如甲方的项目，还有课程制作时间，以及对应的课程主要目标人群，设定的学习时长等等因素。不过您的建议非常棒，如果有机会，可以产生很多合作的机会，我们也很希望聘请您这样有思想深度的开发者直接帮助我们制作课程。
